name: Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
           python-version: 3.11
           
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run shell script
        run: sh project/test.sh 
 