name: Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v1
      run: sh project/test.sh  